# Generated by Django 4.0.4 on 2022-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('station_id', models.IntegerField()),
                ('shelf', models.IntegerField()),
                ('layor', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
        ),
    ]
