# Generated by Django 4.0.4 on 2022-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('iid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('iset', models.CharField(max_length=20)),
                ('iname', models.CharField(max_length=20)),
                ('iaddress', models.CharField(max_length=200)),
                ('ilocation', models.CharField(max_length=16)),
                ('iphone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'identity',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
    ]
