# Generated by Django 4.0.4 on 2022-05-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_identity_delete_user_alter_store_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
    ]
